//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceTelecom
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="https://siat.impuestos.gob.bo/", ConfigurationName="ServiceTelecom.ServicioFacturacion")]
    public interface ServicioFacturacion
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="https://siat.impuestos.gob.bo/ServicioFacturacion/recepcionPaqueteFactura", ReplyAction="https://siat.impuestos.gob.bo/ServicioFacturacion/recepcionPaqueteFacturaResponse" +
            "")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(model))]
        System.Threading.Tasks.Task<ServiceTelecom.recepcionPaqueteFacturaResponse> recepcionPaqueteFacturaAsync(ServiceTelecom.recepcionPaqueteFactura request);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://siat.impuestos.gob.bo/ServicioFacturacion/verificarComunicacion", ReplyAction="https://siat.impuestos.gob.bo/ServicioFacturacion/verificarComunicacionResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(model))]
        System.Threading.Tasks.Task<ServiceTelecom.verificarComunicacionResponse> verificarComunicacionAsync(ServiceTelecom.verificarComunicacion request);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://siat.impuestos.gob.bo/ServicioFacturacion/recepcionFactura", ReplyAction="https://siat.impuestos.gob.bo/ServicioFacturacion/recepcionFacturaResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(model))]
        System.Threading.Tasks.Task<ServiceTelecom.recepcionFacturaResponse> recepcionFacturaAsync(ServiceTelecom.recepcionFactura request);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://siat.impuestos.gob.bo/ServicioFacturacion/validacionRecepcionMasivaFactur" +
            "a", ReplyAction="https://siat.impuestos.gob.bo/ServicioFacturacion/validacionRecepcionMasivaFactur" +
            "aResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(model))]
        System.Threading.Tasks.Task<ServiceTelecom.validacionRecepcionMasivaFacturaResponse> validacionRecepcionMasivaFacturaAsync(ServiceTelecom.validacionRecepcionMasivaFactura request);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://siat.impuestos.gob.bo/ServicioFacturacion/recepcionMasivaFactura", ReplyAction="https://siat.impuestos.gob.bo/ServicioFacturacion/recepcionMasivaFacturaResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(model))]
        System.Threading.Tasks.Task<ServiceTelecom.recepcionMasivaFacturaResponse> recepcionMasivaFacturaAsync(ServiceTelecom.recepcionMasivaFactura request);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://siat.impuestos.gob.bo/ServicioFacturacion/verificacionEstadoFactura", ReplyAction="https://siat.impuestos.gob.bo/ServicioFacturacion/verificacionEstadoFacturaRespon" +
            "se")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(model))]
        System.Threading.Tasks.Task<ServiceTelecom.verificacionEstadoFacturaResponse> verificacionEstadoFacturaAsync(ServiceTelecom.verificacionEstadoFactura request);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://siat.impuestos.gob.bo/ServicioFacturacion/validacionRecepcionPaqueteFactu" +
            "ra", ReplyAction="https://siat.impuestos.gob.bo/ServicioFacturacion/validacionRecepcionPaqueteFactu" +
            "raResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(model))]
        System.Threading.Tasks.Task<ServiceTelecom.validacionRecepcionPaqueteFacturaResponse> validacionRecepcionPaqueteFacturaAsync(ServiceTelecom.validacionRecepcionPaqueteFactura request);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://siat.impuestos.gob.bo/ServicioFacturacion/anulacionFactura", ReplyAction="https://siat.impuestos.gob.bo/ServicioFacturacion/anulacionFacturaResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(model))]
        System.Threading.Tasks.Task<ServiceTelecom.anulacionFacturaResponse> anulacionFacturaAsync(ServiceTelecom.anulacionFactura request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://siat.impuestos.gob.bo/")]
    public partial class solicitudRecepcionPaquete : solicitudRecepcionFactura
    {
        
        private string cafcField;
        
        private int cantidadFacturasField;
        
        private long codigoEventoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string cafc
        {
            get
            {
                return this.cafcField;
            }
            set
            {
                this.cafcField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public int cantidadFacturas
        {
            get
            {
                return this.cantidadFacturasField;
            }
            set
            {
                this.cantidadFacturasField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public long codigoEvento
        {
            get
            {
                return this.codigoEventoField;
            }
            set
            {
                this.codigoEventoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(solicitudRecepcionMasiva))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(solicitudRecepcionPaquete))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://siat.impuestos.gob.bo/")]
    public partial class solicitudRecepcionFactura : solicitudRecepcion
    {
        
        private string archivoField;
        
        private string fechaEnvioField;
        
        private string hashArchivoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string archivo
        {
            get
            {
                return this.archivoField;
            }
            set
            {
                this.archivoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string fechaEnvio
        {
            get
            {
                return this.fechaEnvioField;
            }
            set
            {
                this.fechaEnvioField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string hashArchivo
        {
            get
            {
                return this.hashArchivoField;
            }
            set
            {
                this.hashArchivoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(solicitudAnulacion))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(solicitudVerificacionEstado))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(solicitudValidacionRecepcion))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(solicitudRecepcionFactura))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(solicitudRecepcionMasiva))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(solicitudRecepcionPaquete))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://siat.impuestos.gob.bo/")]
    public partial class solicitudRecepcion : modelDto
    {
        
        private int codigoAmbienteField;
        
        private int codigoDocumentoSectorField;
        
        private int codigoEmisionField;
        
        private int codigoModalidadField;
        
        private int codigoPuntoVentaField;
        
        private bool codigoPuntoVentaFieldSpecified;
        
        private string codigoSistemaField;
        
        private int codigoSucursalField;
        
        private string cufdField;
        
        private string cuisField;
        
        private long nitField;
        
        private int tipoFacturaDocumentoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int codigoAmbiente
        {
            get
            {
                return this.codigoAmbienteField;
            }
            set
            {
                this.codigoAmbienteField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public int codigoDocumentoSector
        {
            get
            {
                return this.codigoDocumentoSectorField;
            }
            set
            {
                this.codigoDocumentoSectorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public int codigoEmision
        {
            get
            {
                return this.codigoEmisionField;
            }
            set
            {
                this.codigoEmisionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public int codigoModalidad
        {
            get
            {
                return this.codigoModalidadField;
            }
            set
            {
                this.codigoModalidadField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public int codigoPuntoVenta
        {
            get
            {
                return this.codigoPuntoVentaField;
            }
            set
            {
                this.codigoPuntoVentaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool codigoPuntoVentaSpecified
        {
            get
            {
                return this.codigoPuntoVentaFieldSpecified;
            }
            set
            {
                this.codigoPuntoVentaFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string codigoSistema
        {
            get
            {
                return this.codigoSistemaField;
            }
            set
            {
                this.codigoSistemaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public int codigoSucursal
        {
            get
            {
                return this.codigoSucursalField;
            }
            set
            {
                this.codigoSucursalField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string cufd
        {
            get
            {
                return this.cufdField;
            }
            set
            {
                this.cufdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public string cuis
        {
            get
            {
                return this.cuisField;
            }
            set
            {
                this.cuisField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public long nit
        {
            get
            {
                return this.nitField;
            }
            set
            {
                this.nitField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        public int tipoFacturaDocumento
        {
            get
            {
                return this.tipoFacturaDocumentoField;
            }
            set
            {
                this.tipoFacturaDocumentoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(respuestaComunicacion))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(mensajeServicio))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(mensajeRecepcion))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(respuestaRecepcion))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(solicitudRecepcion))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(solicitudAnulacion))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(solicitudVerificacionEstado))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(solicitudValidacionRecepcion))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(solicitudRecepcionFactura))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(solicitudRecepcionMasiva))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(solicitudRecepcionPaquete))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://siat.impuestos.gob.bo/")]
    public abstract partial class modelDto : model
    {
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(modelDto))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(respuestaComunicacion))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(mensajeServicio))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(mensajeRecepcion))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(respuestaRecepcion))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(solicitudRecepcion))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(solicitudAnulacion))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(solicitudVerificacionEstado))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(solicitudValidacionRecepcion))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(solicitudRecepcionFactura))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(solicitudRecepcionMasiva))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(solicitudRecepcionPaquete))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://siat.impuestos.gob.bo/")]
    public abstract partial class model
    {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://siat.impuestos.gob.bo/")]
    public partial class respuestaComunicacion : modelDto
    {
        
        private mensajeServicio[] mensajesListField;
        
        private bool transaccionField;
        
        private bool transaccionFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("mensajesList", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=0)]
        public mensajeServicio[] mensajesList
        {
            get
            {
                return this.mensajesListField;
            }
            set
            {
                this.mensajesListField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public bool transaccion
        {
            get
            {
                return this.transaccionField;
            }
            set
            {
                this.transaccionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool transaccionSpecified
        {
            get
            {
                return this.transaccionFieldSpecified;
            }
            set
            {
                this.transaccionFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(mensajeRecepcion))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://siat.impuestos.gob.bo/")]
    public partial class mensajeServicio : modelDto
    {
        
        private int codigoField;
        
        private bool codigoFieldSpecified;
        
        private string descripcionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int codigo
        {
            get
            {
                return this.codigoField;
            }
            set
            {
                this.codigoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool codigoSpecified
        {
            get
            {
                return this.codigoFieldSpecified;
            }
            set
            {
                this.codigoFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string descripcion
        {
            get
            {
                return this.descripcionField;
            }
            set
            {
                this.descripcionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://siat.impuestos.gob.bo/")]
    public partial class mensajeRecepcion : mensajeServicio
    {
        
        private bool advertenciaField;
        
        private bool advertenciaFieldSpecified;
        
        private int numeroArchivoField;
        
        private bool numeroArchivoFieldSpecified;
        
        private int numeroDetalleField;
        
        private bool numeroDetalleFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public bool advertencia
        {
            get
            {
                return this.advertenciaField;
            }
            set
            {
                this.advertenciaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool advertenciaSpecified
        {
            get
            {
                return this.advertenciaFieldSpecified;
            }
            set
            {
                this.advertenciaFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public int numeroArchivo
        {
            get
            {
                return this.numeroArchivoField;
            }
            set
            {
                this.numeroArchivoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool numeroArchivoSpecified
        {
            get
            {
                return this.numeroArchivoFieldSpecified;
            }
            set
            {
                this.numeroArchivoFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public int numeroDetalle
        {
            get
            {
                return this.numeroDetalleField;
            }
            set
            {
                this.numeroDetalleField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool numeroDetalleSpecified
        {
            get
            {
                return this.numeroDetalleFieldSpecified;
            }
            set
            {
                this.numeroDetalleFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://siat.impuestos.gob.bo/")]
    public partial class respuestaRecepcion : modelDto
    {
        
        private string codigoDescripcionField;
        
        private int codigoEstadoField;
        
        private bool codigoEstadoFieldSpecified;
        
        private string codigoRecepcionField;
        
        private mensajeRecepcion[] mensajesListField;
        
        private bool transaccionField;
        
        private bool transaccionFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string codigoDescripcion
        {
            get
            {
                return this.codigoDescripcionField;
            }
            set
            {
                this.codigoDescripcionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public int codigoEstado
        {
            get
            {
                return this.codigoEstadoField;
            }
            set
            {
                this.codigoEstadoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool codigoEstadoSpecified
        {
            get
            {
                return this.codigoEstadoFieldSpecified;
            }
            set
            {
                this.codigoEstadoFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string codigoRecepcion
        {
            get
            {
                return this.codigoRecepcionField;
            }
            set
            {
                this.codigoRecepcionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("mensajesList", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=3)]
        public mensajeRecepcion[] mensajesList
        {
            get
            {
                return this.mensajesListField;
            }
            set
            {
                this.mensajesListField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public bool transaccion
        {
            get
            {
                return this.transaccionField;
            }
            set
            {
                this.transaccionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool transaccionSpecified
        {
            get
            {
                return this.transaccionFieldSpecified;
            }
            set
            {
                this.transaccionFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://siat.impuestos.gob.bo/")]
    public partial class solicitudAnulacion : solicitudRecepcion
    {
        
        private int codigoMotivoField;
        
        private string cufField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int codigoMotivo
        {
            get
            {
                return this.codigoMotivoField;
            }
            set
            {
                this.codigoMotivoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string cuf
        {
            get
            {
                return this.cufField;
            }
            set
            {
                this.cufField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://siat.impuestos.gob.bo/")]
    public partial class solicitudVerificacionEstado : solicitudRecepcion
    {
        
        private string cufField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string cuf
        {
            get
            {
                return this.cufField;
            }
            set
            {
                this.cufField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://siat.impuestos.gob.bo/")]
    public partial class solicitudValidacionRecepcion : solicitudRecepcion
    {
        
        private string codigoRecepcionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string codigoRecepcion
        {
            get
            {
                return this.codigoRecepcionField;
            }
            set
            {
                this.codigoRecepcionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://siat.impuestos.gob.bo/")]
    public partial class solicitudRecepcionMasiva : solicitudRecepcionFactura
    {
        
        private int cantidadFacturasField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int cantidadFacturas
        {
            get
            {
                return this.cantidadFacturasField;
            }
            set
            {
                this.cantidadFacturasField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="recepcionPaqueteFactura", WrapperNamespace="https://siat.impuestos.gob.bo/", IsWrapped=true)]
    public partial class recepcionPaqueteFactura
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://siat.impuestos.gob.bo/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ServiceTelecom.solicitudRecepcionPaquete SolicitudServicioRecepcionPaquete;
        
        public recepcionPaqueteFactura()
        {
        }
        
        public recepcionPaqueteFactura(ServiceTelecom.solicitudRecepcionPaquete SolicitudServicioRecepcionPaquete)
        {
            this.SolicitudServicioRecepcionPaquete = SolicitudServicioRecepcionPaquete;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="recepcionPaqueteFacturaResponse", WrapperNamespace="https://siat.impuestos.gob.bo/", IsWrapped=true)]
    public partial class recepcionPaqueteFacturaResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://siat.impuestos.gob.bo/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ServiceTelecom.respuestaRecepcion RespuestaServicioFacturacion;
        
        public recepcionPaqueteFacturaResponse()
        {
        }
        
        public recepcionPaqueteFacturaResponse(ServiceTelecom.respuestaRecepcion RespuestaServicioFacturacion)
        {
            this.RespuestaServicioFacturacion = RespuestaServicioFacturacion;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="verificarComunicacion", WrapperNamespace="https://siat.impuestos.gob.bo/", IsWrapped=true)]
    public partial class verificarComunicacion
    {
        
        public verificarComunicacion()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="verificarComunicacionResponse", WrapperNamespace="https://siat.impuestos.gob.bo/", IsWrapped=true)]
    public partial class verificarComunicacionResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://siat.impuestos.gob.bo/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ServiceTelecom.respuestaComunicacion @return;
        
        public verificarComunicacionResponse()
        {
        }
        
        public verificarComunicacionResponse(ServiceTelecom.respuestaComunicacion @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="recepcionFactura", WrapperNamespace="https://siat.impuestos.gob.bo/", IsWrapped=true)]
    public partial class recepcionFactura
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://siat.impuestos.gob.bo/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ServiceTelecom.solicitudRecepcionFactura SolicitudServicioRecepcionFactura;
        
        public recepcionFactura()
        {
        }
        
        public recepcionFactura(ServiceTelecom.solicitudRecepcionFactura SolicitudServicioRecepcionFactura)
        {
            this.SolicitudServicioRecepcionFactura = SolicitudServicioRecepcionFactura;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="recepcionFacturaResponse", WrapperNamespace="https://siat.impuestos.gob.bo/", IsWrapped=true)]
    public partial class recepcionFacturaResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://siat.impuestos.gob.bo/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ServiceTelecom.respuestaRecepcion RespuestaServicioFacturacion;
        
        public recepcionFacturaResponse()
        {
        }
        
        public recepcionFacturaResponse(ServiceTelecom.respuestaRecepcion RespuestaServicioFacturacion)
        {
            this.RespuestaServicioFacturacion = RespuestaServicioFacturacion;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="validacionRecepcionMasivaFactura", WrapperNamespace="https://siat.impuestos.gob.bo/", IsWrapped=true)]
    public partial class validacionRecepcionMasivaFactura
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://siat.impuestos.gob.bo/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ServiceTelecom.solicitudValidacionRecepcion SolicitudServicioValidacionRecepcionMasiva;
        
        public validacionRecepcionMasivaFactura()
        {
        }
        
        public validacionRecepcionMasivaFactura(ServiceTelecom.solicitudValidacionRecepcion SolicitudServicioValidacionRecepcionMasiva)
        {
            this.SolicitudServicioValidacionRecepcionMasiva = SolicitudServicioValidacionRecepcionMasiva;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="validacionRecepcionMasivaFacturaResponse", WrapperNamespace="https://siat.impuestos.gob.bo/", IsWrapped=true)]
    public partial class validacionRecepcionMasivaFacturaResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://siat.impuestos.gob.bo/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ServiceTelecom.respuestaRecepcion RespuestaServicioFacturacion;
        
        public validacionRecepcionMasivaFacturaResponse()
        {
        }
        
        public validacionRecepcionMasivaFacturaResponse(ServiceTelecom.respuestaRecepcion RespuestaServicioFacturacion)
        {
            this.RespuestaServicioFacturacion = RespuestaServicioFacturacion;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="recepcionMasivaFactura", WrapperNamespace="https://siat.impuestos.gob.bo/", IsWrapped=true)]
    public partial class recepcionMasivaFactura
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://siat.impuestos.gob.bo/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ServiceTelecom.solicitudRecepcionMasiva SolicitudServicioRecepcionMasiva;
        
        public recepcionMasivaFactura()
        {
        }
        
        public recepcionMasivaFactura(ServiceTelecom.solicitudRecepcionMasiva SolicitudServicioRecepcionMasiva)
        {
            this.SolicitudServicioRecepcionMasiva = SolicitudServicioRecepcionMasiva;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="recepcionMasivaFacturaResponse", WrapperNamespace="https://siat.impuestos.gob.bo/", IsWrapped=true)]
    public partial class recepcionMasivaFacturaResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://siat.impuestos.gob.bo/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ServiceTelecom.respuestaRecepcion RespuestaServicioFacturacion;
        
        public recepcionMasivaFacturaResponse()
        {
        }
        
        public recepcionMasivaFacturaResponse(ServiceTelecom.respuestaRecepcion RespuestaServicioFacturacion)
        {
            this.RespuestaServicioFacturacion = RespuestaServicioFacturacion;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="verificacionEstadoFactura", WrapperNamespace="https://siat.impuestos.gob.bo/", IsWrapped=true)]
    public partial class verificacionEstadoFactura
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://siat.impuestos.gob.bo/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ServiceTelecom.solicitudVerificacionEstado SolicitudServicioVerificacionEstadoFactura;
        
        public verificacionEstadoFactura()
        {
        }
        
        public verificacionEstadoFactura(ServiceTelecom.solicitudVerificacionEstado SolicitudServicioVerificacionEstadoFactura)
        {
            this.SolicitudServicioVerificacionEstadoFactura = SolicitudServicioVerificacionEstadoFactura;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="verificacionEstadoFacturaResponse", WrapperNamespace="https://siat.impuestos.gob.bo/", IsWrapped=true)]
    public partial class verificacionEstadoFacturaResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://siat.impuestos.gob.bo/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ServiceTelecom.respuestaRecepcion RespuestaServicioFacturacion;
        
        public verificacionEstadoFacturaResponse()
        {
        }
        
        public verificacionEstadoFacturaResponse(ServiceTelecom.respuestaRecepcion RespuestaServicioFacturacion)
        {
            this.RespuestaServicioFacturacion = RespuestaServicioFacturacion;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="validacionRecepcionPaqueteFactura", WrapperNamespace="https://siat.impuestos.gob.bo/", IsWrapped=true)]
    public partial class validacionRecepcionPaqueteFactura
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://siat.impuestos.gob.bo/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ServiceTelecom.solicitudValidacionRecepcion SolicitudServicioValidacionRecepcionPaquete;
        
        public validacionRecepcionPaqueteFactura()
        {
        }
        
        public validacionRecepcionPaqueteFactura(ServiceTelecom.solicitudValidacionRecepcion SolicitudServicioValidacionRecepcionPaquete)
        {
            this.SolicitudServicioValidacionRecepcionPaquete = SolicitudServicioValidacionRecepcionPaquete;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="validacionRecepcionPaqueteFacturaResponse", WrapperNamespace="https://siat.impuestos.gob.bo/", IsWrapped=true)]
    public partial class validacionRecepcionPaqueteFacturaResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://siat.impuestos.gob.bo/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ServiceTelecom.respuestaRecepcion RespuestaServicioFacturacion;
        
        public validacionRecepcionPaqueteFacturaResponse()
        {
        }
        
        public validacionRecepcionPaqueteFacturaResponse(ServiceTelecom.respuestaRecepcion RespuestaServicioFacturacion)
        {
            this.RespuestaServicioFacturacion = RespuestaServicioFacturacion;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="anulacionFactura", WrapperNamespace="https://siat.impuestos.gob.bo/", IsWrapped=true)]
    public partial class anulacionFactura
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://siat.impuestos.gob.bo/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ServiceTelecom.solicitudAnulacion SolicitudServicioAnulacionFactura;
        
        public anulacionFactura()
        {
        }
        
        public anulacionFactura(ServiceTelecom.solicitudAnulacion SolicitudServicioAnulacionFactura)
        {
            this.SolicitudServicioAnulacionFactura = SolicitudServicioAnulacionFactura;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="anulacionFacturaResponse", WrapperNamespace="https://siat.impuestos.gob.bo/", IsWrapped=true)]
    public partial class anulacionFacturaResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://siat.impuestos.gob.bo/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ServiceTelecom.respuestaRecepcion RespuestaServicioFacturacion;
        
        public anulacionFacturaResponse()
        {
        }
        
        public anulacionFacturaResponse(ServiceTelecom.respuestaRecepcion RespuestaServicioFacturacion)
        {
            this.RespuestaServicioFacturacion = RespuestaServicioFacturacion;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    public interface ServicioFacturacionChannel : ServiceTelecom.ServicioFacturacion, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    public partial class ServicioFacturacionClient : System.ServiceModel.ClientBase<ServiceTelecom.ServicioFacturacion>, ServiceTelecom.ServicioFacturacion
    {
        
        public ServicioFacturacionClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceTelecom.recepcionPaqueteFacturaResponse> ServiceTelecom.ServicioFacturacion.recepcionPaqueteFacturaAsync(ServiceTelecom.recepcionPaqueteFactura request)
        {
            return base.Channel.recepcionPaqueteFacturaAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceTelecom.recepcionPaqueteFacturaResponse> recepcionPaqueteFacturaAsync(ServiceTelecom.solicitudRecepcionPaquete SolicitudServicioRecepcionPaquete)
        {
            ServiceTelecom.recepcionPaqueteFactura inValue = new ServiceTelecom.recepcionPaqueteFactura();
            inValue.SolicitudServicioRecepcionPaquete = SolicitudServicioRecepcionPaquete;
            return ((ServiceTelecom.ServicioFacturacion)(this)).recepcionPaqueteFacturaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceTelecom.verificarComunicacionResponse> ServiceTelecom.ServicioFacturacion.verificarComunicacionAsync(ServiceTelecom.verificarComunicacion request)
        {
            return base.Channel.verificarComunicacionAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceTelecom.verificarComunicacionResponse> verificarComunicacionAsync()
        {
            ServiceTelecom.verificarComunicacion inValue = new ServiceTelecom.verificarComunicacion();
            return ((ServiceTelecom.ServicioFacturacion)(this)).verificarComunicacionAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceTelecom.recepcionFacturaResponse> ServiceTelecom.ServicioFacturacion.recepcionFacturaAsync(ServiceTelecom.recepcionFactura request)
        {
            return base.Channel.recepcionFacturaAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceTelecom.recepcionFacturaResponse> recepcionFacturaAsync(ServiceTelecom.solicitudRecepcionFactura SolicitudServicioRecepcionFactura)
        {
            ServiceTelecom.recepcionFactura inValue = new ServiceTelecom.recepcionFactura();
            inValue.SolicitudServicioRecepcionFactura = SolicitudServicioRecepcionFactura;
            return ((ServiceTelecom.ServicioFacturacion)(this)).recepcionFacturaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceTelecom.validacionRecepcionMasivaFacturaResponse> ServiceTelecom.ServicioFacturacion.validacionRecepcionMasivaFacturaAsync(ServiceTelecom.validacionRecepcionMasivaFactura request)
        {
            return base.Channel.validacionRecepcionMasivaFacturaAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceTelecom.validacionRecepcionMasivaFacturaResponse> validacionRecepcionMasivaFacturaAsync(ServiceTelecom.solicitudValidacionRecepcion SolicitudServicioValidacionRecepcionMasiva)
        {
            ServiceTelecom.validacionRecepcionMasivaFactura inValue = new ServiceTelecom.validacionRecepcionMasivaFactura();
            inValue.SolicitudServicioValidacionRecepcionMasiva = SolicitudServicioValidacionRecepcionMasiva;
            return ((ServiceTelecom.ServicioFacturacion)(this)).validacionRecepcionMasivaFacturaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceTelecom.recepcionMasivaFacturaResponse> ServiceTelecom.ServicioFacturacion.recepcionMasivaFacturaAsync(ServiceTelecom.recepcionMasivaFactura request)
        {
            return base.Channel.recepcionMasivaFacturaAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceTelecom.recepcionMasivaFacturaResponse> recepcionMasivaFacturaAsync(ServiceTelecom.solicitudRecepcionMasiva SolicitudServicioRecepcionMasiva)
        {
            ServiceTelecom.recepcionMasivaFactura inValue = new ServiceTelecom.recepcionMasivaFactura();
            inValue.SolicitudServicioRecepcionMasiva = SolicitudServicioRecepcionMasiva;
            return ((ServiceTelecom.ServicioFacturacion)(this)).recepcionMasivaFacturaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceTelecom.verificacionEstadoFacturaResponse> ServiceTelecom.ServicioFacturacion.verificacionEstadoFacturaAsync(ServiceTelecom.verificacionEstadoFactura request)
        {
            return base.Channel.verificacionEstadoFacturaAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceTelecom.verificacionEstadoFacturaResponse> verificacionEstadoFacturaAsync(ServiceTelecom.solicitudVerificacionEstado SolicitudServicioVerificacionEstadoFactura)
        {
            ServiceTelecom.verificacionEstadoFactura inValue = new ServiceTelecom.verificacionEstadoFactura();
            inValue.SolicitudServicioVerificacionEstadoFactura = SolicitudServicioVerificacionEstadoFactura;
            return ((ServiceTelecom.ServicioFacturacion)(this)).verificacionEstadoFacturaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceTelecom.validacionRecepcionPaqueteFacturaResponse> ServiceTelecom.ServicioFacturacion.validacionRecepcionPaqueteFacturaAsync(ServiceTelecom.validacionRecepcionPaqueteFactura request)
        {
            return base.Channel.validacionRecepcionPaqueteFacturaAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceTelecom.validacionRecepcionPaqueteFacturaResponse> validacionRecepcionPaqueteFacturaAsync(ServiceTelecom.solicitudValidacionRecepcion SolicitudServicioValidacionRecepcionPaquete)
        {
            ServiceTelecom.validacionRecepcionPaqueteFactura inValue = new ServiceTelecom.validacionRecepcionPaqueteFactura();
            inValue.SolicitudServicioValidacionRecepcionPaquete = SolicitudServicioValidacionRecepcionPaquete;
            return ((ServiceTelecom.ServicioFacturacion)(this)).validacionRecepcionPaqueteFacturaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceTelecom.anulacionFacturaResponse> ServiceTelecom.ServicioFacturacion.anulacionFacturaAsync(ServiceTelecom.anulacionFactura request)
        {
            return base.Channel.anulacionFacturaAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceTelecom.anulacionFacturaResponse> anulacionFacturaAsync(ServiceTelecom.solicitudAnulacion SolicitudServicioAnulacionFactura)
        {
            ServiceTelecom.anulacionFactura inValue = new ServiceTelecom.anulacionFactura();
            inValue.SolicitudServicioAnulacionFactura = SolicitudServicioAnulacionFactura;
            return ((ServiceTelecom.ServicioFacturacion)(this)).anulacionFacturaAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
    }
}
